### PR TITLE
Updated journal

### PR DESCRIPTION
**Pull request by Ricecoder**

### CODE REVIEW

**Comment by cmauban** [comment]
I completely agree with the visuals of the CSS being easier! I love how we can just tweak things and figure them out through trial and error. Good job on View Mode Switch and breaking your code into three separate parts. I wish I did that from the start! :+1:

**Comment by karjac14** [comment]
It's good to know you enjoy CSS, I have to agree that seeing visuals changes really make us all feel better. Thanks for the tutorial as well about resolving conflicts in git. :+1:

**Comment by ericquayson** [comment]
I like your point about organizing your code by the different views and also utilizing the comments to describe each html element. :+1:

**Comment by jmcreasman** [comment]
Any tutorial on Merge Conflicts gets a :+1: from me! I will be bookmarking this

**Pull request merged**
