### PR TITLE
Made final changes to rough draft

### PR DESCRIPTION
**Pull request by Ricecoder**

### CODE REVIEW

**Comment by cmauban** [comment]
Great overview of last week! You're really good at breaking down the code in English and writing it step-by-step. That is something I need to work on! :+1:

**Comment by karjac14** [comment]
Its great how you interconnected all the things we learned last week for us to come up bigger complicated tasks. :+1:  Great work Lacey!

**Comment by jmcreasman** [comment]
Great summary on what we went over that week. Although the DOM does feel like a mob boss at times :p 
:+1:

**Comment by jeremyrist** [comment]
:+1: Great job, Lacey! Keep up the good work and thank you for all your patience with my questions :)

**Comment by boshnivolo** [comment]
Solid essay. It was very well-structured. :+1:

**Pull request merged**
